name: "HiLook NVR MQTT"
version: "1.0.0"
slug: "hilook_nvr_mqtt"
description: "Listens TCP from HiLook/Hikvision NVR, publishes motion events to MQTT"
url: "https://github.com/Pestkov/ha-addons"
arch:
  - aarch64
  - armv7
  - amd64
startup: application
boot: auto
init: false
ports:
  6062/tcp: 6062
ports_description:
  6062/tcp: "NVR TCP listener"
options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  nvr_port: 6062
  motion_timeout: 30
schema:
  mqtt_host: str
  mqtt_port: int
  nvr_port: int
  motion_timeout: int
